// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customer

// Input for adding a product to cart
type AddToCartInput struct {
	// ID of the product to add
	ProductID string `json:"productId"`
	// Number of units to add (default: 1)
	Quantity *int `json:"quantity,omitempty"`
}

type Mutation struct {
}

// Input for placing an order
type PlaceOrderInput struct {
	// Customer's name
	CustomerName string `json:"customerName"`
	// Customer's email address
	CustomerEmail string `json:"customerEmail"`
	// Shipping address
	ShippingAddress string `json:"shippingAddress"`
}

// Input for updating cart item quantity
type UpdateCartItemInput struct {
	// ID of the product to update
	ProductID string `json:"productId"`
	// New quantity (0 removes the item)
	Quantity int `json:"quantity"`
}
