// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Represents the shopping cart
type Cart struct {
	// Unique identifier for the cart. It's immutable once created
	ID string `json:"id"`
	// List of items in the cart
	Items []*CartItem `json:"items"`
	// Total price of all items in the cart. This may be different from the sum of all items as discounts and other promotions may apply
	TotalPrice int `json:"totalPrice"`
}

// Represents an item in the shopping cart
type CartItem struct {
	// The product snapshot in the cart
	Product *Product `json:"product"`
	// Number of units of this product in the cart
	Quantity int `json:"quantity"`
	// Total price for this cart item (pricePerUnit * quantity)
	TotalPrice int `json:"totalPrice"`
}

// Represents a customer order
type Order struct {
	// Unique identifier for the order
	ID string `json:"id"`
	// Customer's name
	CustomerName string `json:"customerName"`
	// Customer's email address
	CustomerEmail string `json:"customerEmail"`
	// Shipping address
	ShippingAddress string `json:"shippingAddress"`
	// List of items in the order
	Items []*OrderItem `json:"items"`
	// Total price of the order
	TotalPrice int `json:"totalPrice"`
	// Current state of the order
	State OrderState `json:"state"`
	// Timestamp when the order was placed
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the order was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// A paginated list of orders
type OrderConnection struct {
	// List of orders in this page
	Edges []*OrderEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in the order connection
type OrderEdge struct {
	// The order
	Node *Order `json:"node"`
	// Cursor for this order
	Cursor string `json:"cursor"`
}

// Represents an item in an order
type OrderItem struct {
	// The product snapshot that was ordered
	Product *Product `json:"product"`
	// Number of units ordered
	Quantity int `json:"quantity"`
	// Total price for this order item
	TotalPrice int `json:"totalPrice"`
}

// Information about pagination in a connection
type PageInfo struct {
	// Whether there are more items after this page
	HasNextPage bool `json:"hasNextPage"`
	// Whether there are more items before this page
	HasPreviousPage bool `json:"hasPreviousPage"`
	// Cursor to the first item in this page
	StartCursor *string `json:"startCursor,omitempty"`
	// Cursor to the last item in this page
	EndCursor *string `json:"endCursor,omitempty"`
	// Total number of items across all pages
	TotalCount int `json:"totalCount"`
}

// Represents a product in the shop
type Product struct {
	// Unique identifier for the product
	ID string `json:"id"`
	// Display name of the product
	Name string `json:"name"`
	// Detailed description of the product
	Description *string `json:"description,omitempty"`
	// Image data for the product. The value follows the data URI scheme (e.g., 'data:image/png;base64,...')
	ImageData *string `json:"imageData,omitempty"`
	// Price per unit in cents
	PricePerUnit int `json:"pricePerUnit"`
	// Number of units currently in stock
	CountInStock int `json:"countInStock"`
	// Current availability state
	State ProductState `json:"state"`
	// Timestamp when the product was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the product was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// A paginated list of products
type ProductConnection struct {
	// List of products in this page
	Edges []*ProductEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
}

// An edge in the product connection
type ProductEdge struct {
	// The product
	Node *Product `json:"node"`
	// Cursor for this product
	Cursor string `json:"cursor"`
}

type Query struct {
}

// State representing order lifecycle
// The valid state transitions are:
// - PROCESSING -> SHIPPED (when order is dispatched)
// - PROCESSING -> CANCELED (when order is canceled before shipping)
// - SHIPPED -> COMPLETED (when order is delivered)
// - SHIPPED -> CANCELED (when order is canceled after shipping)
type OrderState string

const (
	// Order has been placed and is being processed
	OrderStateProcessing OrderState = "PROCESSING"
	// Order has been shipped
	OrderStateShipped OrderState = "SHIPPED"
	// Order has been delivered and completed
	OrderStateCompleted OrderState = "COMPLETED"
	// Order has been canceled
	OrderStateCanceled OrderState = "CANCELED"
)

var AllOrderState = []OrderState{
	OrderStateProcessing,
	OrderStateShipped,
	OrderStateCompleted,
	OrderStateCanceled,
}

func (e OrderState) IsValid() bool {
	switch e {
	case OrderStateProcessing, OrderStateShipped, OrderStateCompleted, OrderStateCanceled:
		return true
	}
	return false
}

func (e OrderState) String() string {
	return string(e)
}

func (e *OrderState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderState", str)
	}
	return nil
}

func (e OrderState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// State representing product availability for customers
type ProductState string

const (
	// Product is available for purchase
	ProductStateAvailable ProductState = "AVAILABLE"
	// Product is currently off shelf and not available
	ProductStateOffShelf ProductState = "OFF_SHELF"
)

var AllProductState = []ProductState{
	ProductStateAvailable,
	ProductStateOffShelf,
}

func (e ProductState) IsValid() bool {
	switch e {
	case ProductStateAvailable, ProductStateOffShelf:
		return true
	}
	return false
}

func (e ProductState) String() string {
	return string(e)
}

func (e *ProductState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductState", str)
	}
	return nil
}

func (e ProductState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
