# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.demoshop.v1 import transaction_pb2 as proto_dot_demoshop_dot_v1_dot_transaction__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/demoshop/v1/transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    InventoryService manages product inventory
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryProducts = channel.unary_unary(
                '/demoshop.v1.InventoryService/QueryProducts',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/demoshop.v1.InventoryService/GetProduct',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/demoshop.v1.InventoryService/CreateProduct',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/demoshop.v1.InventoryService/UpdateProduct',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/demoshop.v1.InventoryService/DeleteProduct',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    InventoryService manages product inventory
    """

    def QueryProducts(self, request, context):
        """Query products with pagination and optional filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Get a single product by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Create a new product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Update an existing product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Delete a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryProducts,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demoshop.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demoshop.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    InventoryService manages product inventory
    """

    @staticmethod
    def QueryProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.InventoryService/QueryProducts',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.InventoryService/GetProduct',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.InventoryService/CreateProduct',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.InventoryService/UpdateProduct',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.InventoryService/DeleteProduct',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CartServiceStub(object):
    """CartService manages shopping carts
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCart = channel.unary_unary(
                '/demoshop.v1.CartService/GetCart',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.AddProductToCart = channel.unary_unary(
                '/demoshop.v1.CartService/AddProductToCart',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartResponse.FromString,
                _registered_method=True)
        self.UpdateProductInCart = channel.unary_unary(
                '/demoshop.v1.CartService/UpdateProductInCart',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/demoshop.v1.CartService/ClearCart',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartResponse.FromString,
                _registered_method=True)


class CartServiceServicer(object):
    """CartService manages shopping carts
    """

    def GetCart(self, request, context):
        """Get cart by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProductToCart(self, request, context):
        """Add a product to cart
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductInCart(self, request, context):
        """Update product quantity in cart (set to 0 to remove)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Clear all items from cart
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartResponse.SerializeToString,
            ),
            'AddProductToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProductToCart,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartResponse.SerializeToString,
            ),
            'UpdateProductInCart': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductInCart,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demoshop.v1.CartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demoshop.v1.CartService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CartService(object):
    """CartService manages shopping carts
    """

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.CartService/GetCart',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProductToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.CartService/AddProductToCart',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.AddProductToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductInCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.CartService/UpdateProductInCart',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateProductInCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.CartService/ClearCart',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrderServiceStub(object):
    """OrderService manages customer orders
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/demoshop.v1.OrderService/CreateOrder',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.QueryOrders = channel.unary_unary(
                '/demoshop.v1.OrderService/QueryOrders',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/demoshop.v1.OrderService/GetOrder',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderResponse.FromString,
                _registered_method=True)
        self.UpdateOrder = channel.unary_unary(
                '/demoshop.v1.OrderService/UpdateOrder',
                request_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderRequest.SerializeToString,
                response_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """OrderService manages customer orders
    """

    def CreateOrder(self, request, context):
        """Create a new order from cart contents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOrders(self, request, context):
        """Query orders with pagination and optional filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Get a single order by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrder(self, request, context):
        """Update order state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderResponse.SerializeToString,
            ),
            'QueryOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOrders,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderResponse.SerializeToString,
            ),
            'UpdateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrder,
                    request_deserializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderRequest.FromString,
                    response_serializer=proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demoshop.v1.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demoshop.v1.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """OrderService manages customer orders
    """

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.OrderService/CreateOrder',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.OrderService/QueryOrders',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.QueryOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.OrderService/GetOrder',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.GetOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demoshop.v1.OrderService/UpdateOrder',
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderRequest.SerializeToString,
            proto_dot_demoshop_dot_v1_dot_transaction__pb2.UpdateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
