// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package admin

import (
	"demoshop/pkg/frontend/graphql/types"
)

// Input for creating a new product (Admin)
type CreateProductInput struct {
	// Display name of the product
	Name string `json:"name"`
	// Detailed description of the product
	Description *string `json:"description,omitempty"`
	// Image data for the product. The value follows the data URI scheme (e.g., 'data:image/png;base64,...')
	ImageData *string `json:"imageData,omitempty"`
	// Price per unit in cents
	PricePerUnit int `json:"pricePerUnit"`
	// Number of units in stock
	CountInStock int `json:"countInStock"`
	// Initial availability state (default: AVAILABLE)
	State *types.ProductState `json:"state,omitempty"`
}

type Mutation struct {
}

// Filter options for orders (Admin)
type OrderFilterInput struct {
	// Filter by order state
	State *types.OrderState `json:"state,omitempty"`
	// Filter by customer email
	CustomerEmail *string `json:"customerEmail,omitempty"`
}

// Filter options for products (Admin)
type ProductFilterInput struct {
	// Filter by product state
	State *types.ProductState `json:"state,omitempty"`
	// Search by name (case-insensitive partial match)
	SearchName *string `json:"searchName,omitempty"`
}

// Input for updating an existing product (Admin)
type UpdateProductInput struct {
	// ID of the product to update
	ID string `json:"id"`
	// New display name
	Name *string `json:"name,omitempty"`
	// New description
	Description *string `json:"description,omitempty"`
	// New image data for the product. The value follows the data URI scheme (e.g., 'data:image/png;base64,...')
	ImageData *string `json:"imageData,omitempty"`
	// New price per unit in cents
	PricePerUnit *int `json:"pricePerUnit,omitempty"`
	// New count in stock
	CountInStock *int `json:"countInStock,omitempty"`
	// New availability state
	State *types.ProductState `json:"state,omitempty"`
}
